#library(mlbench)
#library(tidyverse)
#install.packages("readr")
library(caret)
library(readr)
library(stats)
library(gbm)
library(C50)
library(rpart)
library(klaR)
heart_disease <- read_csv("data/clean_cardio_train.csv")
heart_disease <- subset(heart_disease, select = -c(ID))
load("models.RData")